import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { GeneralProvider } from "@/contexts/GeneralAppStateContext";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const YekanBakh = localFont({
  src: [
    {
      path: "./fonts/YEKANBAKH-EXTRABLACK.woff",
      weight: "950",
      style: "normal",
    },
    {
      path: "./fonts/YEKANBAKH-BLACK.woff",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/YEKANBAKH-EXTRABOLD.woff",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/YEKANBAKH-BOLD.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/YEKANBAKH-SEMIBOLD.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/YEKANBAKH-REGULAR.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/YEKANBAKH-LIGHT.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/YEKANBAKH-THIN.woff",
      weight: "200",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={YekanBakh.className}>
        <GeneralProvider>{children}</GeneralProvider>
      </body>
    </html>
  );
}
